# Generated by Django 6.0.2 on 2026-03-02 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_collaboration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('note', 'user')},
        ),
    ]
